-- =====================================================================
--  Kemence Akadémia — TELJES adatbázis-séma (egyetlen igazságforrás)
--  Supabase / PostgreSQL. Bemásolható a Supabase → SQL Editor-ba.
--
--  KONVENCIÓ: ez a fájl MINDIG a legfrissebb, teljes sémát tartalmazza.
--  Egy ÜRES projektnél elég EZT lefuttatni — minden benne van (táblák,
--  biztonság, logika). Éles telepítésnél nulláról ezt futtatjuk.
--  A storage-bucket és a levél-automatika külön fájlokban van:
--  02-storage.sql, 03-auto-visszaigazolo-trigger.sql, 04-emlekezteto-cron.sql.
--
--  Tartalom: workshops (program) + idopontok (alkalmak) + bookings + settings
--  + biztonság (RLS) + szabad-helyek logika + túlfoglalás elleni védelem.
--
--  MODELL: egy PROGRAM (workshops) több IDŐPONTHOZ (idopontok) tartozhat;
--  egy FOGLALÁS (bookings) mindig egy konkrét IDŐPONTRA szól (idopont_id).
--  Az ár, kedvezményes ár, létszám és az „elmaradt" állapot IDŐPONTONKÉNT
--  értendő; a cím/leírás/előadó/kép a programhoz (közös) tartozik.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) PROGRAMOK (workshops) — a program KÖZÖS adatai (minden időpontra)
-- ---------------------------------------------------------------------
create table if not exists public.workshops (
  id                 uuid primary key default gen_random_uuid(),
  cim                text        not null,
  rovid_leiras       text,                    -- rövid leírás a kártyára (kötelező az adminban)
  leiras             text,                    -- részletes leírás (OPCIONÁLIS), a „Részletek" ablakban
  eloado             text,                    -- előadó(k) neve; akár több név vesszővel („Szabó Zoltán, Nagy Andrea")
  varhato_idotartam  text,                    -- pl. "~4 óra"; opcionális
  foto_url           text,                    -- Storage-link; opcionális
  statusz            text not null default 'aktiv'
                       check (statusz in ('aktiv','hamarosan')),  -- 'hamarosan' = még nincs meghirdetett időpont
  archivalt          boolean not null default false,   -- ha true: nem jelenik meg a főoldalon
  foglalas_felfuggesztve boolean not null default false, -- átmeneti szünet: a publikus foglalás tiltva erre a programra
  created_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2) IDŐPONTOK (idopontok) — egy program egy-egy meghirdetett alkalma
--    Ár/kedvezményes ár/létszám IDŐPONTONKÉNT; státusz: aktiv / elmaradt.
-- ---------------------------------------------------------------------
create table if not exists public.idopontok (
  id                 uuid primary key default gen_random_uuid(),
  workshop_id        uuid not null references public.workshops(id) on delete cascade,
  idopont            timestamptz not null,        -- dátum + idő
  ar                 integer not null,            -- Ft
  kedvezmenyes_ar    integer,                     -- opcionális akciós ár (< ar)
  max_letszam        integer not null,            -- férőhely erre az alkalomra
  max_foglalasok     integer,                     -- hány FOGLALÁS jöhet rá (null = korlátlan)
  min_letszam        integer,                     -- egy foglalás MIN. létszáma (null = nincs)
  statusz            text not null default 'aktiv'
                       check (statusz in ('aktiv','elmaradt')),   -- 'elmaradt' = ez az alkalom lemondva
  created_at         timestamptz not null default now(),

  -- akciós ár csak az alap ár alatt lehet
  constraint idopont_kedvezmeny_kisebb
    check (kedvezmenyes_ar is null or kedvezmenyes_ar < ar),
  constraint idopont_letszam_pozitiv
    check (max_letszam > 0),
  -- csoportos korlátok: pozitív értékek, és a minimum nem nagyobb a kapacitásnál
  constraint idopont_max_foglalasok_pozitiv
    check (max_foglalasok is null or max_foglalasok >= 1),
  constraint idopont_min_letszam_ervenyes
    check (min_letszam is null or (min_letszam >= 1 and min_letszam <= max_letszam))
);

-- ---------------------------------------------------------------------
-- 3) FOGLALÁSOK (bookings) — mindig egy KONKRÉT IDŐPONTRA (idopont_id)
-- ---------------------------------------------------------------------
create table if not exists public.bookings (
  id           uuid primary key default gen_random_uuid(),
  azonosito    bigint generated by default as identity (start with 1),     -- belső sorszám 1-től; megjelenítve: elotag + (azonosito + kezdo - 1)
  idopont_id   uuid not null references public.idopontok(id) on delete restrict,
  nev          text    not null,
  email        text    not null,
  telefon      text    not null,
  letszam      integer not null check (letszam > 0),
  megjegyzes   text,
  statusz      text not null default 'jovahagyasra_var'
                 check (statusz in ('jovahagyasra_var','jovahagyott','elutasitott','lemondott')),
  created_at   timestamptz not null default now()
);

create index if not exists workshops_archivalt_idx on public.workshops (archivalt);
create index if not exists idopontok_workshop_idx   on public.idopontok (workshop_id);
create index if not exists idopontok_idopont_idx     on public.idopontok (idopont);
create index if not exists bookings_idopont_idx      on public.bookings (idopont_id);
create index if not exists bookings_statusz_idx      on public.bookings (statusz);
create unique index if not exists bookings_azonosito_uniq on public.bookings (azonosito);

-- ---------------------------------------------------------------------
-- 4) BEÁLLÍTÁSOK (settings) — egysoros tábla
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  id                integer primary key default 1 check (id = 1),
  levelezesi_email  text,
  foglalas_infosav  text,                     -- a foglalási űrlap info-sávja (admin állíthatja)
  azonosito_elotag  text    not null default 'F-'  check (char_length(azonosito_elotag) <= 2),
  azonosito_kezdo   integer not null default 100   check (azonosito_kezdo between 1 and 999),
  naptar_nezet      text    not null default 'lista' check (naptar_nezet in ('lista','racs')),  -- admin naptár nézet
  foglalas_szunet   boolean not null default false,   -- globális „minden foglalás" szünet (a publikus foglalás tiltva)
  updated_at        timestamptz not null default now()
);

-- A csapat e-mail címet (levelezesi_email) szándékosan NEM töltjük ki:
-- az adminnak kell megadnia a Beállítások fülön (ez a válaszcím és az értesítők címzettje).
insert into public.settings (id, levelezesi_email, foglalas_infosav)
values (1, null,
  'A foglalás jóváhagyásához előre utalás szükséges. Beküldés után felvesszük veled a kapcsolatot; a foglalás addig „jóváhagyásra vár” állapotban van.')
on conflict (id) do nothing;

-- E-mail sablonok (az admin szerkeszti). Behelyettesíthető mezők a tárgyban/törzsben:
--   {nev} {program} {idopont} {letszam} {azonosito}
create table if not exists public.email_sablonok (
  tipus      text primary key
               check (tipus in ('jovahagyas','elutasitas','lemondas','visszaigazolas','csapat_ertesito','program_elmarad','emlekezteto')),
  targy      text not null,
  torzs      text not null,
  updated_at timestamptz not null default now()
);

insert into public.email_sablonok (tipus, targy, torzs) values
('visszaigazolas',
 'Foglalásod megkaptuk – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nKöszönjük a foglalásod! A(z) {program} ({idopont}) programra {letszam} fő jelentkezésedet rögzítettük.\n\nA foglalás jelenleg jóváhagyásra vár. Hamarosan felvesszük veled a kapcsolatot az előre utalás egyeztetéséhez, és a foglalást annak beérkezése után hagyjuk jóvá.\n\nFoglalási azonosító: {azonosito}\n\nÜdvözlettel,\nKemence Akadémia'),
('csapat_ertesito',
 'Új foglalás – {program} ({azonosito})',
 E'Új foglalás érkezett.\n\nAzonosító: {azonosito}\nProgram: {program}\nIdőpont: {idopont}\nLétszám: {letszam} fő\n\nFoglaló: {nev}\nE-mail: {email}\nTelefon: {telefon}\n\nA foglalás jóváhagyásra vár az admin felületen.'),
('jovahagyas',
 'Foglalásod jóváhagyva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nÖrömmel értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat jóváhagytuk. Létszám: {letszam} fő.\n\nSzeretettel várunk!\nKemence Akadémia'),
('elutasitas',
 'Foglalásod elutasítva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nSajnálattal értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat elutasítottuk.\n\nHa kérdésed van, keress minket bizalommal.\n\nÜdvözlettel,\nKemence Akadémia'),
('lemondas',
 'Foglalásod lemondva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nA(z) {program} ({idopont}) programra szóló foglalásodat lemondtuk. Létszám: {letszam} fő.\n\nHa ez tévedés, kérjük jelezd felénk.\n\nÜdvözlettel,\nKemence Akadémia'),
('program_elmarad',
 'A program elmarad – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nSajnálattal értesítünk, hogy a(z) {program} ({idopont}) program sajnos elmarad.\n\nElnézést kérünk a kellemetlenségért. Ha kérdésed van, keress minket bizalommal.\n\nÜdvözlettel,\nKemence Akadémia'),
('emlekezteto',
 'Emlékeztető: holnap {program} – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nEmlékeztetünk, hogy holnap, {idopont} időpontban kerül megrendezésre a(z) {program}, amelyre {letszam} fő jelentkezésedet rögzítettük.\n\nSzeretettel várunk! Ha bármi közbejött, kérjük mielőbb jelezd a válasz e-mailben.\n\nFoglalási azonosító: {azonosito}\n\nÜdvözlettel,\nKemence Akadémia')
on conflict (tipus) do nothing;

-- Kiküldött e-mailek naplója (csak a tény: booking + tipus + időpont; tartalmat nem tárol)
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  tipus      text not null,   -- visszaigazolas / csapat_ertesito / jovahagyas / elutasitas / lemondas / emlekezteto
  cimzett    text,
  elkuldve   timestamptz not null default now()
);
create index if not exists email_log_booking_idx on public.email_log (booking_id);

-- ---------------------------------------------------------------------
-- 5) SZABAD HELYEK — foglalt helyek számolása IDŐPONTONKÉNT
--    security definer: anon is meg tudja hívni, de a foglalások
--    SORAIT nem látja — csak az összesített számot kapja meg.
-- ---------------------------------------------------------------------
create or replace function public.foglalt_helyek(p_idopont uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(letszam), 0)::int
  from public.bookings
  where idopont_id = p_idopont
    and statusz in ('jovahagyasra_var','jovahagyott');  -- ezek foglalnak helyet
$$;

-- Élő foglalások SZÁMA egy időponton (a max_foglalasok korláthoz).
create or replace function public.foglalasok_szama(p_idopont uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::int
  from public.bookings
  where idopont_id = p_idopont
    and statusz in ('jovahagyasra_var','jovahagyott');
$$;

-- Publikus programlista nézet: program-mezők × időpontok + szabad helyek,
-- foglalási sorok kiszivárgása nélkül. LEFT JOIN, hogy az időpont nélküli
-- ('hamarosan') program is megjelenjen (idopont_id = null sorral).
drop view if exists public.programok;
create view public.programok as
select
  w.id                as workshop_id,
  w.cim, w.rovid_leiras, w.leiras, w.eloado, w.varhato_idotartam, w.foto_url,
  w.archivalt, w.foglalas_felfuggesztve,
  w.statusz           as program_statusz,     -- 'aktiv' / 'hamarosan'
  i.id                as idopont_id,          -- null, ha a programnak nincs időpontja
  i.idopont,
  i.ar, i.kedvezmenyes_ar, i.max_letszam,
  i.max_foglalasok, i.min_letszam,
  i.statusz           as idopont_statusz,     -- 'aktiv' / 'elmaradt'
  case when i.id is null then null
       else greatest(coalesce(i.max_letszam,0) - public.foglalt_helyek(i.id), 0)
  end                 as szabad_helyek,
  case when i.id is null then null
       else public.foglalasok_szama(i.id)
  end                 as foglalasok_szama
from public.workshops w
left join public.idopontok i on i.workshop_id = w.id;

-- ---------------------------------------------------------------------
-- 6) TÚLFOGLALÁS ELLENI VÉDELEM — trigger (időpont-szinten)
--    Foglalás beszúrásakor/módosításakor ellenőrzi a szabad helyet,
--    az időpont és a program állapotát.
-- ---------------------------------------------------------------------
create or replace function public.ellenoriz_szabad_hely()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_max          integer;
  v_ido_statusz  text;
  v_idopont      timestamptz;
  v_prog_statusz text;
  v_archivalt    boolean;
  v_felfugg      boolean;
  v_szunet       boolean;
  v_maxfogl      integer;
  v_min          integer;
  v_foglalt      integer;
  v_fogl_szam    integer;
begin
  -- Csak a helyet foglaló (aktív) státuszoknál ellenőrzünk: így lezárt foglalás
  -- (lemondott/elutasított) bármikor módosítható elmaradt/archivált időponton is.
  if new.statusz in ('jovahagyasra_var','jovahagyott') then
    select i.max_letszam, i.statusz, i.idopont, w.statusz, w.archivalt, w.foglalas_felfuggesztve,
           i.max_foglalasok, i.min_letszam
      into v_max, v_ido_statusz, v_idopont, v_prog_statusz, v_archivalt, v_felfugg,
           v_maxfogl, v_min
    from public.idopontok i
    join public.workshops w on w.id = i.workshop_id
    where i.id = new.idopont_id;

    if not found then
      raise exception 'Ismeretlen időpont.';
    end if;

    if v_ido_statusz = 'elmaradt' then
      raise exception 'Ez az időpont elmaradt, nem foglalható.';
    end if;

    if v_prog_statusz is distinct from 'aktiv' or coalesce(v_archivalt, false) then
      raise exception 'Erre a programra nem lehet foglalni (nem aktív).';
    end if;

    -- Szünet: a PUBLIKUS (anon) foglalást felfüggesztjük (program-szintű vagy globális).
    select foglalas_szunet into v_szunet from public.settings where id = 1;
    if tg_op = 'INSERT' and coalesce(auth.role(), '') = 'anon'
       and (coalesce(v_felfugg, false) or coalesce(v_szunet, false)) then
      raise exception 'A foglalás erre a programra jelenleg átmenetileg szünetel.';
    end if;

    -- Publikus (anon) foglalás NEM mehet MÚLTBÉLI időpontra; a mai nap még OK.
    -- Az admin / seed (nem anon) rögzíthet historikus adatot (pl. lezajlott alkalom).
    if tg_op = 'INSERT'
       and coalesce(auth.role(), '') = 'anon'
       and v_idopont is not null
       and (v_idopont at time zone 'Europe/Budapest')::date
           < (now()      at time zone 'Europe/Budapest')::date then
      raise exception 'Erre az időpontra már nem lehet foglalni (lezárult).';
    end if;

    -- Min. létszám / foglalás — csak a publikus (anon) foglalásra (az admin felülbírálhatja).
    if tg_op = 'INSERT' and coalesce(auth.role(), '') = 'anon'
       and v_min is not null and new.letszam < v_min then
      raise exception 'Erre az időpontra legalább % fős foglalás szükséges.', v_min;
    end if;

    -- Max. foglalások száma — csak a publikus (anon) foglalásra.
    if tg_op = 'INSERT' and coalesce(auth.role(), '') = 'anon' and v_maxfogl is not null then
      select count(*) into v_fogl_szam
      from public.bookings
      where idopont_id = new.idopont_id
        and statusz in ('jovahagyasra_var','jovahagyott')
        and id <> new.id;
      if v_fogl_szam >= v_maxfogl then
        raise exception 'Erre az időpontra már nem fogadható több foglalás.';
      end if;
    end if;

    select coalesce(sum(letszam),0) into v_foglalt
    from public.bookings
    where idopont_id = new.idopont_id
      and statusz in ('jovahagyasra_var','jovahagyott')
      and id <> new.id;                        -- saját magát ne számolja (update)

    if v_foglalt + new.letszam > coalesce(v_max,0) then
      raise exception 'Nincs elég szabad hely (% szabad).',
        greatest(coalesce(v_max,0) - v_foglalt, 0);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_szabad_hely on public.bookings;
create trigger trg_szabad_hely
  before insert or update on public.bookings
  for each row execute function public.ellenoriz_szabad_hely();

-- ---------------------------------------------------------------------
-- 7) BIZTONSÁG (Row Level Security)
--    Alapelv: a publikus látogató olvashat programot/időpontot és beküldhet
--    foglalást, de foglalási adatokat NEM lát. Mindent más csak a
--    bejelentkezett admin.
-- ---------------------------------------------------------------------
alter table public.workshops      enable row level security;
alter table public.idopontok      enable row level security;
alter table public.bookings       enable row level security;
alter table public.settings       enable row level security;
alter table public.email_sablonok enable row level security;
alter table public.email_log      enable row level security;

-- --- workshops ---
drop policy if exists workshops_read on public.workshops;
create policy workshops_read on public.workshops
  for select using (true);                                   -- bárki olvashatja

drop policy if exists workshops_admin on public.workshops;
create policy workshops_admin on public.workshops
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- idopontok ---
drop policy if exists idopontok_read on public.idopontok;
create policy idopontok_read on public.idopontok
  for select using (true);                                   -- bárki olvashatja

drop policy if exists idopontok_admin on public.idopontok;
create policy idopontok_admin on public.idopontok
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- bookings ---
drop policy if exists bookings_public_insert on public.bookings;
create policy bookings_public_insert on public.bookings           -- bárki beküldhet,
  for insert to anon, authenticated
  with check (statusz = 'jovahagyasra_var');                       -- de csak "vár" státusszal

drop policy if exists bookings_admin_read on public.bookings;
create policy bookings_admin_read on public.bookings
  for select to authenticated using (auth.uid() is not null);

drop policy if exists bookings_admin_update on public.bookings;
create policy bookings_admin_update on public.bookings
  for update to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists bookings_admin_delete on public.bookings;
create policy bookings_admin_delete on public.bookings
  for delete to authenticated using (auth.uid() is not null);

-- --- settings ---
drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings
  for select using (true);                                   -- a feladó cím olvasható

drop policy if exists settings_admin on public.settings;
create policy settings_admin on public.settings
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- email_sablonok (csak admin; a publikus nem látja) ---
drop policy if exists email_sablonok_admin on public.email_sablonok;
create policy email_sablonok_admin on public.email_sablonok
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- email_log (csak admin olvashatja; írás service-role-lal) ---
drop policy if exists email_log_read on public.email_log;
create policy email_log_read on public.email_log
  for select to authenticated using (auth.uid() is not null);

-- ---------------------------------------------------------------------
-- 8) JOGOSULTSÁGOK a publikus programlistához
-- ---------------------------------------------------------------------
grant select  on public.programok       to anon, authenticated;
grant execute on function public.foglalt_helyek(uuid) to anon, authenticated;

-- ---------------------------------------------------------------------
-- 9) LÁTOGATÁS-SZÁMLÁLÓ (egyszerű, globális; RLS mögött, csak függvényen át)
-- ---------------------------------------------------------------------
create table if not exists public.oldal_statisztika (
  id           integer primary key default 1 check (id = 1),
  latogatasok  bigint not null default 0,
  updated_at   timestamptz not null default now()
);
insert into public.oldal_statisztika (id, latogatasok)
values (1, 0) on conflict (id) do nothing;
alter table public.oldal_statisztika enable row level security;

create or replace function public.latogatas_rogzites()
returns bigint language sql security definer set search_path = public as $$
  update public.oldal_statisztika
     set latogatasok = latogatasok + 1, updated_at = now()
   where id = 1
  returning latogatasok;
$$;
create or replace function public.latogatas_szam()
returns bigint language sql security definer set search_path = public as $$
  select latogatasok from public.oldal_statisztika where id = 1;
$$;
grant execute on function public.latogatas_rogzites() to anon, authenticated;
grant execute on function public.latogatas_szam()     to anon, authenticated;

-- =====================================================================
--  Kész. A "workshops" (program) + "idopontok" (alkalmak) + "bookings"
--  (foglalás egy időpontra) + "settings" táblák állnak, a publikus
--  "programok" nézet program × időpont bontásban mutatja a szabad helyeket,
--  és a foglalás nem tud túlfoglalni. Az e-mail SABLONOK is benne vannak.
-- =====================================================================
--
--  AMI EBBEN A FÁJLBAN NINCS (mert projekt-specifikus értékek kellenek hozzá):
--   • Automatikus visszaigazoló + csapat-értesítő  → db/03-auto-visszaigazolo-trigger.sql
--   • Napi emlékeztető (pg_cron)                    → db/04-emlekezteto-cron.sql
--  Ezek trigger/cron + pg_net/pg_cron, és a <PROJECT_REF>/<ANON_KEY> értéket
--  bele kell írni (Supabase → Project Settings → API). Éles telepítés: lásd install.html.
-- =====================================================================
