-- =====================================================================
--  Kemence Akadémia — TELJES adatbázis-séma (egyetlen igazságforrás)
--  Supabase / PostgreSQL. Bemásolható a Supabase → SQL Editor-ba.
--
--  KONVENCIÓ: ez a fájl MINDIG a legfrissebb, teljes sémát tartalmazza.
--  Egy ÜRES projektnél elég EZT lefuttatni — minden benne van (táblák,
--  biztonság, logika). Éles telepítésnél nulláról ezt futtatjuk.
--  A storage-bucket és a levél-automatika külön fájlokban van:
--  02-storage.sql, 03-auto-visszaigazolo-trigger.sql, 04-emlekezteto-cron.sql.
--
--  Tartalom: workshops, bookings, settings + biztonság (RLS) +
--  szabad-helyek logika + túlfoglalás elleni védelem.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) PROGRAMOK (workshops)
-- ---------------------------------------------------------------------
create table if not exists public.workshops (
  id                 uuid primary key default gen_random_uuid(),
  cim                text        not null,
  leiras             text        not null,
  ar                 integer,                 -- Ft; "aktív" programnál kötelező
  kedvezmenyes_ar    integer,                 -- opcionális akciós ár
  idopont            timestamptz,             -- dátum + idő; "aktív"-nál kötelező
  varhato_idotartam  text,                    -- pl. "~4 óra"; opcionális
  max_letszam        integer,                 -- "aktív"-nál kötelező
  foto_url           text,                    -- Storage-link; opcionális
  statusz            text not null default 'aktiv'
                       check (statusz in ('aktiv','hamarosan','elmaradt')),  -- elmaradt = a program lemondva
  archivalt          boolean not null default false,   -- ha true: nem jelenik meg a főoldalon
  created_at         timestamptz not null default now(),

  -- akciós ár csak az alap ár alatt lehet
  constraint kedvezmeny_kisebb
    check (kedvezmenyes_ar is null
           or (ar is not null and kedvezmenyes_ar < ar)),

  -- "aktív" (foglalható) programnál kötelező az ár, időpont, létszám;
  -- "hamarosan" státusznál csak a cím és a leírás kell
  constraint aktiv_kotelezo
    check (statusz <> 'aktiv'
           or (ar is not null and idopont is not null and max_letszam is not null)),

  constraint letszam_pozitiv
    check (max_letszam is null or max_letszam > 0)
);

-- ---------------------------------------------------------------------
-- 2) FOGLALÁSOK (bookings)
-- ---------------------------------------------------------------------
create table if not exists public.bookings (
  id           uuid primary key default gen_random_uuid(),
  azonosito    bigint generated by default as identity (start with 1),     -- belső sorszám 1-től; megjelenítve: elotag + (azonosito + kezdo - 1)
  workshop_id  uuid not null references public.workshops(id) on delete restrict,
  nev          text    not null,
  email        text    not null,
  telefon      text    not null,
  letszam      integer not null check (letszam > 0),
  megjegyzes   text,
  statusz      text not null default 'jovahagyasra_var'
                 check (statusz in ('jovahagyasra_var','jovahagyott','elutasitott','lemondott')),
  created_at   timestamptz not null default now()
);

create index if not exists workshops_archivalt_idx on public.workshops (archivalt);
create index if not exists bookings_workshop_idx on public.bookings (workshop_id);
create index if not exists bookings_statusz_idx   on public.bookings (statusz);
create unique index if not exists bookings_azonosito_uniq on public.bookings (azonosito);

-- ---------------------------------------------------------------------
-- 3) BEÁLLÍTÁSOK (settings) — egysoros tábla
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  id                integer primary key default 1 check (id = 1),
  levelezesi_email  text,
  foglalas_infosav  text,                     -- a foglalási űrlap info-sávja (admin állíthatja)
  azonosito_elotag  text    not null default 'F-'  check (char_length(azonosito_elotag) <= 2),
  azonosito_kezdo   integer not null default 100   check (azonosito_kezdo between 1 and 999),
  updated_at        timestamptz not null default now()
);

insert into public.settings (id, levelezesi_email, foglalas_infosav)
values (1, 'akademia@mobilkemence.xyz',
  'A foglalás jóváhagyásához előre utalás szükséges. Beküldés után felvesszük veled a kapcsolatot; a foglalás addig „jóváhagyásra vár” állapotban van.')
on conflict (id) do nothing;

-- E-mail sablonok (az admin szerkeszti). Behelyettesíthető mezők a tárgyban/törzsben:
--   {nev} {program} {idopont} {letszam} {azonosito}
create table if not exists public.email_sablonok (
  tipus      text primary key
               check (tipus in ('jovahagyas','elutasitas','lemondas','visszaigazolas','csapat_ertesito','program_elmarad','emlekezteto')),
  targy      text not null,
  torzs      text not null,
  updated_at timestamptz not null default now()
);

insert into public.email_sablonok (tipus, targy, torzs) values
('visszaigazolas',
 'Foglalásod megkaptuk – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nKöszönjük a foglalásod! A(z) {program} ({idopont}) programra {letszam} fő jelentkezésedet rögzítettük.\n\nA foglalás jelenleg jóváhagyásra vár. Hamarosan felvesszük veled a kapcsolatot az előre utalás egyeztetéséhez, és a foglalást annak beérkezése után hagyjuk jóvá.\n\nFoglalási azonosító: {azonosito}\n\nÜdvözlettel,\nKemence Akadémia'),
('csapat_ertesito',
 'Új foglalás – {program} ({azonosito})',
 E'Új foglalás érkezett.\n\nAzonosító: {azonosito}\nProgram: {program}\nIdőpont: {idopont}\nLétszám: {letszam} fő\n\nFoglaló: {nev}\nE-mail: {email}\nTelefon: {telefon}\n\nA foglalás jóváhagyásra vár az admin felületen.'),
('jovahagyas',
 'Foglalásod jóváhagyva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nÖrömmel értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat jóváhagytuk. Létszám: {letszam} fő.\n\nSzeretettel várunk!\nKemence Akadémia'),
('elutasitas',
 'Foglalásod elutasítva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nSajnálattal értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat elutasítottuk.\n\nHa kérdésed van, keress minket bizalommal.\n\nÜdvözlettel,\nKemence Akadémia'),
('lemondas',
 'Foglalásod lemondva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nA(z) {program} ({idopont}) programra szóló foglalásodat lemondtuk. Létszám: {letszam} fő.\n\nHa ez tévedés, kérjük jelezd felénk.\n\nÜdvözlettel,\nKemence Akadémia'),
('program_elmarad',
 'A program elmarad – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nSajnálattal értesítünk, hogy a(z) {program} ({idopont}) program sajnos elmarad.\n\nElnézést kérünk a kellemetlenségért. Ha kérdésed van, keress minket bizalommal.\n\nÜdvözlettel,\nKemence Akadémia'),
('emlekezteto',
 'Emlékeztető: holnap {program} – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nEmlékeztetünk, hogy holnap, {idopont} időpontban kerül megrendezésre a(z) {program}, amelyre {letszam} fő jelentkezésedet rögzítettük.\n\nSzeretettel várunk! Ha bármi közbejött, kérjük mielőbb jelezd a válasz e-mailben.\n\nFoglalási azonosító: {azonosito}\n\nÜdvözlettel,\nKemence Akadémia')
on conflict (tipus) do nothing;

-- Kiküldött e-mailek naplója (csak a tény: booking + tipus + időpont; tartalmat nem tárol)
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  tipus      text not null,   -- visszaigazolas / csapat_ertesito / jovahagyas / elutasitas / lemondas / emlekezteto
  cimzett    text,
  elkuldve   timestamptz not null default now()
);
create index if not exists email_log_booking_idx on public.email_log (booking_id);

-- ---------------------------------------------------------------------
-- 4) SZABAD HELYEK — foglalt helyek számolása
--    security definer: anon is meg tudja hívni, de a foglalások
--    SORAIT nem látja — csak az összesített számot kapja meg.
-- ---------------------------------------------------------------------
create or replace function public.foglalt_helyek(p_workshop uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(letszam), 0)::int
  from public.bookings
  where workshop_id = p_workshop
    and statusz in ('jovahagyasra_var','jovahagyott');  -- ezek foglalnak helyet
$$;

-- Publikus programlista nézet: workshop-mezők + szabad helyek,
-- foglalási sorok kiszivárgása nélkül.
drop view if exists public.programok;
create view public.programok as
select
  w.id, w.cim, w.leiras, w.ar, w.kedvezmenyes_ar, w.idopont,
  w.varhato_idotartam, w.foto_url, w.statusz, w.max_letszam, w.archivalt,
  greatest(coalesce(w.max_letszam,0) - public.foglalt_helyek(w.id), 0) as szabad_helyek
from public.workshops w;

-- ---------------------------------------------------------------------
-- 5) TÚLFOGLALÁS ELLENI VÉDELEM — trigger
--    Foglalás beszúrásakor/módosításakor ellenőrzi a szabad helyet.
-- ---------------------------------------------------------------------
create or replace function public.ellenoriz_szabad_hely()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_max     integer;
  v_statusz text;
  v_idopont timestamptz;
  v_foglalt integer;
begin
  -- Csak a helyet foglaló (aktív) státuszoknál ellenőrzünk: így lezárt foglalás
  -- (lemondott/elutasított) bármikor módosítható elmaradt/archivált programon is.
  if new.statusz in ('jovahagyasra_var','jovahagyott') then
    select max_letszam, statusz, idopont into v_max, v_statusz, v_idopont
    from public.workshops where id = new.workshop_id;

    if v_statusz is distinct from 'aktiv' then
      raise exception 'Erre a programra nem lehet foglalni (nem aktív).';
    end if;

    -- Publikus (anon) foglalás NEM mehet MÚLTBÉLI eseményre; a mai nap még OK.
    -- Az admin / seed (nem anon) rögzíthet historikus adatot (pl. lezajlott program).
    if tg_op = 'INSERT'
       and coalesce(auth.role(), '') = 'anon'
       and v_idopont is not null
       and (v_idopont at time zone 'Europe/Budapest')::date
           < (now()      at time zone 'Europe/Budapest')::date then
      raise exception 'Erre a programra már nem lehet foglalni (lezárult).';
    end if;

    select coalesce(sum(letszam),0) into v_foglalt
    from public.bookings
    where workshop_id = new.workshop_id
      and statusz in ('jovahagyasra_var','jovahagyott')
      and id <> new.id;                        -- saját magát ne számolja (update)

    if v_foglalt + new.letszam > coalesce(v_max,0) then
      raise exception 'Nincs elég szabad hely (% szabad).',
        greatest(coalesce(v_max,0) - v_foglalt, 0);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_szabad_hely on public.bookings;
create trigger trg_szabad_hely
before insert or update on public.bookings
for each row execute function public.ellenoriz_szabad_hely();

-- ---------------------------------------------------------------------
-- 6) BIZTONSÁG (Row Level Security)
--    Alapelv: a publikus látogató olvashat programot és beküldhet
--    foglalást, de foglalási adatokat NEM lát. Mindent más csak a
--    bejelentkezett admin.
--    (Egyetlen admin fiók lesz, önregisztráció nincs → minden
--     bejelentkezett = admin. Később szűkíthető konkrét e-mailre.)
-- ---------------------------------------------------------------------
alter table public.workshops      enable row level security;
alter table public.bookings       enable row level security;
alter table public.settings       enable row level security;
alter table public.email_sablonok enable row level security;
alter table public.email_log      enable row level security;

-- --- workshops ---
drop policy if exists workshops_read on public.workshops;
create policy workshops_read on public.workshops
  for select using (true);                                   -- bárki olvashatja

drop policy if exists workshops_admin on public.workshops;
create policy workshops_admin on public.workshops
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- bookings ---
drop policy if exists bookings_public_insert on public.bookings;
create policy bookings_public_insert on public.bookings           -- bárki beküldhet,
  for insert to anon, authenticated
  with check (statusz = 'jovahagyasra_var');                       -- de csak "vár" státusszal

drop policy if exists bookings_admin_read on public.bookings;
create policy bookings_admin_read on public.bookings
  for select to authenticated using (auth.uid() is not null);

drop policy if exists bookings_admin_update on public.bookings;
create policy bookings_admin_update on public.bookings
  for update to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists bookings_admin_delete on public.bookings;
create policy bookings_admin_delete on public.bookings
  for delete to authenticated using (auth.uid() is not null);

-- --- settings ---
drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings
  for select using (true);                                   -- a feladó cím olvasható

drop policy if exists settings_admin on public.settings;
create policy settings_admin on public.settings
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- email_sablonok (csak admin; a publikus nem látja) ---
drop policy if exists email_sablonok_admin on public.email_sablonok;
create policy email_sablonok_admin on public.email_sablonok
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- --- email_log (csak admin olvashatja; írás service-role-lal) ---
drop policy if exists email_log_read on public.email_log;
create policy email_log_read on public.email_log
  for select to authenticated using (auth.uid() is not null);

-- ---------------------------------------------------------------------
-- 7) JOGOSULTSÁGOK a publikus programlistához
-- ---------------------------------------------------------------------
grant select  on public.programok       to anon, authenticated;
grant execute on function public.foglalt_helyek(uuid) to anon, authenticated;

-- ---------------------------------------------------------------------
-- 8) LÁTOGATÁS-SZÁMLÁLÓ (egyszerű, globális; RLS mögött, csak függvényen át)
-- ---------------------------------------------------------------------
create table if not exists public.oldal_statisztika (
  id           integer primary key default 1 check (id = 1),
  latogatasok  bigint not null default 0,
  updated_at   timestamptz not null default now()
);
insert into public.oldal_statisztika (id, latogatasok)
values (1, 0) on conflict (id) do nothing;
alter table public.oldal_statisztika enable row level security;

create or replace function public.latogatas_rogzites()
returns bigint language sql security definer set search_path = public as $$
  update public.oldal_statisztika
     set latogatasok = latogatasok + 1, updated_at = now()
   where id = 1
  returning latogatasok;
$$;
create or replace function public.latogatas_szam()
returns bigint language sql security definer set search_path = public as $$
  select latogatasok from public.oldal_statisztika where id = 1;
$$;
grant execute on function public.latogatas_rogzites() to anon, authenticated;
grant execute on function public.latogatas_szam()     to anon, authenticated;

-- =====================================================================
--  Kész. A "workshops"/"bookings"/"settings" táblák állnak,
--  a publikus "programok" nézet mutatja a szabad helyeket,
--  és a foglalás nem tud túlfoglalni. Az e-mail SABLONOK is benne vannak.
-- =====================================================================
--
--  AMI EBBEN A FÁJLBAN NINCS (mert projekt-specifikus értékek kellenek hozzá):
--   • Automatikus visszaigazoló + csapat-értesítő  → db/03-auto-visszaigazolo-trigger.sql
--   • Napi emlékeztető (pg_cron)                    → db/04-emlekezteto-cron.sql
--  Ezek trigger/cron + pg_net/pg_cron, és a <PROJECT_REF>/<ANON_KEY> értéket
--  bele kell írni (Supabase → Project Settings → API). Éles telepítés: lásd install.html.
-- =====================================================================
