-- =====================================================================
--  Migráció: foglalási azonosító (sorszám) + e-mail sablonok.
--  Futtasd a már meglévő DB-n. (A 01-schema.sql frissítve van ezekkel.)
-- =====================================================================

-- ---- 1) Ember-barát foglalási azonosító (#1000-től) ----
alter table public.bookings
  add column if not exists azonosito bigint generated by default as identity (start with 100);

create unique index if not exists bookings_azonosito_uniq on public.bookings (azonosito);

-- ---- 2) E-mail sablonok tábla ----
--  Behelyettesíthető mezők a tárgyban/törzsben: {nev} {program} {idopont} {letszam} {azonosito}
create table if not exists public.email_sablonok (
  tipus      text primary key
               check (tipus in ('jovahagyas','elutasitas','lemondas','visszaigazolas','emlekezteto')),
  targy      text not null,
  torzs      text not null,
  updated_at timestamptz not null default now()
);

-- ---- 3) Alapértelmezett sablonok (az admin később átírhatja) ----
insert into public.email_sablonok (tipus, targy, torzs) values
('jovahagyas',
 'Foglalásod jóváhagyva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nÖrömmel értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat jóváhagytuk. Létszám: {letszam} fő.\n\nSzeretettel várunk!\nKemence Akadémia'),
('elutasitas',
 'Foglalásod elutasítva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nSajnálattal értesítünk, hogy a(z) {program} ({idopont}) programra szóló foglalásodat elutasítottuk.\n\nHa kérdésed van, keress minket bizalommal.\n\nÜdvözlettel,\nKemence Akadémia'),
('lemondas',
 'Foglalásod lemondva – Kemence Akadémia ({azonosito})',
 E'Kedves {nev}!\n\nA(z) {program} ({idopont}) programra szóló foglalásodat lemondtuk. Létszám: {letszam} fő.\n\nHa ez tévedés, kérjük jelezd felénk.\n\nÜdvözlettel,\nKemence Akadémia')
on conflict (tipus) do nothing;

-- ---- 4) Biztonság: a sablonokat csak a bejelentkezett admin kezelheti ----
alter table public.email_sablonok enable row level security;

drop policy if exists email_sablonok_admin on public.email_sablonok;
create policy email_sablonok_admin on public.email_sablonok
  for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);
