-- =====================================================================
--  Migráció: kiküldött e-mailek naplója (melyik levél ment ki, mikor).
--  Tartalmat NEM tárol, csak a tényt: booking + tipus + időpont.
--  A küldő háttér (Edge Function) ide ír majd; most demó-adattal töltjük.
-- =====================================================================

create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  tipus      text not null,   -- visszaigazolas / csapat_ertesito / jovahagyas / elutasitas / lemondas / emlekezteto
  cimzett    text,            -- kinek ment (e-mail cím) — opcionális
  elkuldve   timestamptz not null default now()
);

create index if not exists email_log_booking_idx on public.email_log (booking_id);

-- Biztonság: csak a bejelentkezett admin olvashatja. (Írás a küldő háttérből,
-- service-role joggal történik, ami az RLS-t megkerüli.)
alter table public.email_log enable row level security;
drop policy if exists email_log_read on public.email_log;
create policy email_log_read on public.email_log
  for select to authenticated using (auth.uid() is not null);

-- =====================================================================
--  TESZT demo-napló (opcionális) — hogy az adminban látszódjon a funkció.
--  Minden foglaláshoz "visszaigazolas"; a lezárt/jóváhagyott állapotokhoz
--  a megfelelő státusz-levél is. (Újrafuttatható: előbb üríti.)
-- =====================================================================
delete from public.email_log;

insert into public.email_log (booking_id, tipus, cimzett, elkuldve)
  select id, 'visszaigazolas', email, created_at from public.bookings;
insert into public.email_log (booking_id, tipus, cimzett, elkuldve)
  select id, 'jovahagyas', email, created_at + interval '2 hours' from public.bookings where statusz = 'jovahagyott';
insert into public.email_log (booking_id, tipus, cimzett, elkuldve)
  select id, 'lemondas', email, created_at + interval '2 hours' from public.bookings where statusz = 'lemondott';
insert into public.email_log (booking_id, tipus, cimzett, elkuldve)
  select id, 'elutasitas', email, created_at + interval '2 hours' from public.bookings where statusz = 'elutasitott';
