-- =====================================================================
--  Migráció: a foglalási azonosító formátuma az admin által állítható.
--    settings.azonosito_elotag  (max 2 karakter, alap: 'F-')
--    settings.azonosito_kezdo   (1–999, alap: 100)
--  Megjelenített szám = elotag + (bookings.azonosito + kezdo - 1).
--  A belső sorszámot 1-től indítjuk (a kezdő így tiszta eltolás).
--  Futtasd a már meglévő DB-n. (A 01-schema.sql frissítve van ezekkel.)
-- =====================================================================

-- ---- 1) Beállítás-mezők ----
alter table public.settings
  add column if not exists azonosito_elotag text not null default 'F-';
alter table public.settings
  add column if not exists azonosito_kezdo integer not null default 100;

alter table public.settings drop constraint if exists azonosito_elotag_hossz;
alter table public.settings add constraint azonosito_elotag_hossz
  check (char_length(azonosito_elotag) <= 2);

alter table public.settings drop constraint if exists azonosito_kezdo_tart;
alter table public.settings add constraint azonosito_kezdo_tart
  check (azonosito_kezdo between 1 and 999);

-- ---- 2) Belső sorszám induljon 1-től ----
--  (Teszt-adat, ezért a mező tiszta újraépítése a legegyszerűbb. Az email_log
--   a bookings.id-ra hivatkozik, nem az azonositóra, így ez nem érinti.)
alter table public.bookings drop column if exists azonosito;
alter table public.bookings
  add column azonosito bigint generated by default as identity (start with 1);
create unique index if not exists bookings_azonosito_uniq on public.bookings (azonosito);
